# Generated by Django 3.2.9 on 2022-01-08 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220107_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(height_field=200, upload_to='event_images', verbose_name='Event Image', width_field=100),
        ),
    ]
